# Generated by Django 4.0.6 on 2022-07-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_autorization_degree_alter_autorization_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
