# Generated by Django 4.0.6 on 2022-07-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_notes_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.autorization'),
        ),
    ]
