# Generated by Django 4.0.6 on 2022-08-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_datesforbirthday_h_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.CharField(choices=[('2022-08-01', '01-08-2022'), ('2022-08-08', '08-08-2022')], max_length=50, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='hour',
            field=models.IntegerField(default=0, verbose_name='Всего'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='lec',
            field=models.IntegerField(default=0, verbose_name='Лекции'),
        ),
    ]
