# Generated by Django 4.0.6 on 2022-09-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_autorization_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.CharField(choices=[('2022-09-05', '05-09-2022'), ('2022-08-29', '29-08-2022'), ('2022-08-22', '22-08-2022')], max_length=50, null=True, verbose_name='Дата'),
        ),
    ]
