# Generated by Django 4.0.6 on 2022-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_notes_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='login',
            field=models.CharField(max_length=50, verbose_name='Логин'),
        ),
    ]
