# Generated by Django 4.0.6 on 2022-07-25 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.DateField(choices=[(datetime.date(2022, 5, 2), '2022-05-02'), (datetime.date(2022, 7, 4), '2022-07-04')], null=True, verbose_name='Дата'),
        ),
    ]
