# Generated by Django 4.0.6 on 2022-07-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_autorization_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorization',
            name='dad',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='autorization',
            name='degree',
            field=models.CharField(choices=[('ктн', 'ктн'), ('дтн', 'дтн'), ('квн', 'квн'), ('двн', 'двн'), ('отс', 'отсутствует')], default='отс', max_length=3),
        ),
        migrations.AddField(
            model_name='autorization',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='autorization',
            name='rank',
            field=models.CharField(choices=[('ЛЙ', 'лейтенант'), ('СЛ', 'старший лейтенант'), ('КП', 'капитан'), ('МЙ', 'майор'), ('ПД', 'подполковник'), ('ПЛ', 'полковник'), ('ГМ', 'генерал-майор'), ('ГЛ', 'генерал-лейтенант'), ('ГП', 'генерал-полковник'), ('ГА', 'генерал армии'), ('ОТ', 'отсутствует')], default='ЛЙ', max_length=2),
        ),
        migrations.AddField(
            model_name='autorization',
            name='scientist',
            field=models.CharField(choices=[('доц', 'доц'), ('про', 'проф'), ('снс', 'снс'), ('отс', 'отсутствует')], default='отс', max_length=3),
        ),
    ]
