# Generated by Django 4.0.6 on 2022-08-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_datesforbirthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesforbirthday',
            name='h_b',
            field=models.IntegerField(null=True, verbose_name='За сколько?'),
        ),
    ]
