# Generated by Django 4.0.6 on 2022-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст'),
        ),
    ]
