# Generated by Django 4.0.6 on 2022-07-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_autorization_is_admin_autorization_is_not_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorization',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='autorization',
            name='is_not_print',
            field=models.BooleanField(default=False, verbose_name='Не выводить'),
        ),
    ]
