# Generated by Django 4.0.6 on 2022-08-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_autorization_rank_alter_notes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorization',
            name='rank',
            field=models.CharField(choices=[('ЛЙ', 'лейтенант'), ('СЛ', 'старший лейтенант'), ('КП', 'капитан'), ('МЙ', 'майор'), ('ПД', 'подполковник'), ('ПЛ', 'полковник'), ('ГМ', 'генерал-майор'), ('ГЛ', 'генерал-лейтенант'), ('ГП', 'генерал-полковник'), ('ГА', 'генерал армии'), ('ОТ', 'отсутствует')], default='ЛЙ', max_length=2, verbose_name='в/звание'),
        ),
    ]
