# Generated by Django 4.1.3 on 2022-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_remove_autorization_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="data",
            field=models.CharField(
                choices=[("2022-11-28", "28-11-2022")],
                max_length=50,
                null=True,
                verbose_name="Дата",
            ),
        ),
    ]
