# Generated by Django 4.0.6 on 2022-12-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_notes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorization',
            name='degree',
            field=models.CharField(choices=[('ктн', 'ктн'), ('дтн', 'дтн'), ('квн', 'квн'), ('двн', 'двн'), ('отс', 'отсутствует'), ('кфм', 'кфмн'), ('дфм', 'дфмн'), ('кэн', 'кэн'), ('дэн', 'дэн'), ('кпн', 'кпн'), ('дпн', 'дпн')], default='отс', max_length=3, verbose_name='уч.степень'),
        ),
        migrations.AlterField(
            model_name='autorization',
            name='post',
            field=models.CharField(choices=[('НК', 'заведующий кафедрой'), ('ЗК', 'заместитель заведующего кафедрой'), ('ПР', 'профессор'), ('ДЦ', 'доцент'), ('СП', 'старший преподаватель'), ('ПР', 'преподаватель'), ('ДК', 'докторант'), ('АД', 'аспирант'), ('СН', 'старший научный сотрудник'), ('НЛ', 'заведующий лабораторией'), ('ИО', 'инженер'), ('ИП', 'программист'), ('ЛБ', 'лаборант'), ('ТХ', 'техник'), ('АС', 'ассистент'), ('СЛ', 'старший лаборант'), ('НУ', 'научный сотрудник'), ('МУ', 'младший научный сотрудник')], default='ПР', max_length=2, verbose_name='должность'),
        ),
    ]
