# Generated by Django 4.0.6 on 2022-07-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_autorization_birthday_alter_autorization_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorization',
            name='degree',
            field=models.CharField(choices=[('ктн', 'ктн'), ('дтн', 'дтн'), ('квн', 'квн'), ('двн', 'двн'), ('отс', 'отсутствует')], default='отс', max_length=3, verbose_name='уч.степень'),
        ),
        migrations.AlterField(
            model_name='autorization',
            name='rank',
            field=models.CharField(choices=[('ЛЙ', 'лейтенант'), ('СЛ', 'старший лейтенант'), ('КП', 'капитан'), ('МЙ', 'майор'), ('ПД', 'подполковник'), ('ПЛ', 'полковник'), ('ГМ', 'генерал-майор'), ('ГЛ', 'генерал-лейтенант'), ('ГП', 'генерал-полковник'), ('ГА', 'генерал армии'), ('ОТ', 'отсутствует')], default='ЛЙ', max_length=2, verbose_name='в/звание'),
        ),
        migrations.AlterField(
            model_name='autorization',
            name='scientist',
            field=models.CharField(choices=[('доц', 'доц'), ('про', 'проф'), ('снс', 'снс'), ('отс', 'отсутствует')], default='отс', max_length=3, verbose_name='уч.звание'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.autorization')),
            ],
        ),
    ]
