# Generated by Django 4.0.6 on 2022-08-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_notes_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='hour',
            field=models.IntegerField(null=True, verbose_name='Всего'),
        ),
        migrations.AddField(
            model_name='notes',
            name='lec',
            field=models.IntegerField(null=True, verbose_name='Лекции'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.CharField(choices=[('2022-07-25', '2022-07-25'), ('2022-08-01', '2022-08-01')], max_length=50, null=True, verbose_name='Дата'),
        ),
    ]
