# Generated by Django 4.0.6 on 2022-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_autorization_dad_autorization_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorization',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='autorization',
            name='degree',
            field=models.CharField(choices=[('ктн', 'ктн'), ('дтн', 'дтн'), ('квн', 'квн'), ('двн', 'двн'), ('отс', 'отсутствует')], default='отс', max_length=3, verbose_name='уч.звание'),
        ),
        migrations.AlterField(
            model_name='autorization',
            name='post',
            field=models.CharField(choices=[('НК', 'начальник кафедры'), ('ЗК', 'заместитель начальника кафедры'), ('ПР', 'профессор'), ('ДЦ', 'доцент'), ('СП', 'старший преподаватель'), ('ПР', 'преподаватель'), ('ДК', 'докторант'), ('АД', 'адъюнкт'), ('СН', 'старший научный сотрудник'), ('ЗН', 'заместитель начальника факультета'), ('НЛ', 'начальник лаборатории'), ('НО', 'начальник отделения'), ('ИО', 'инженер отделения'), ('ИП', 'инженер-программист отделения'), ('РМ', 'радиомеханик'), ('ЛБ', 'лаборант'), ('ТХ', 'техник')], default='ПР', max_length=2, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='autorization',
            name='rank',
            field=models.CharField(choices=[('ЛЙ', 'лейтенант'), ('СЛ', 'старший лейтенант'), ('КП', 'капитан'), ('МЙ', 'майор'), ('ПД', 'подполковник'), ('ПЛ', 'полковник'), ('ГМ', 'генерал-майор'), ('ГЛ', 'генерал-лейтенант'), ('ГП', 'генерал-полковник'), ('ГА', 'генерал армии'), ('ОТ', 'отсутствует')], default='ЛЙ', max_length=2, verbose_name='уч.степень'),
        ),
        migrations.AlterField(
            model_name='autorization',
            name='scientist',
            field=models.CharField(choices=[('доц', 'доц'), ('про', 'проф'), ('снс', 'снс'), ('отс', 'отсутствует')], default='отс', max_length=3, verbose_name='в/звание'),
        ),
    ]
