# Generated by Django 4.0.6 on 2022-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_notes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorization',
            name='rank',
            field=models.CharField(choices=[('ЛЙ', 'лейтенант'), ('СЛ', 'старший лейтенант'), ('КП', 'капитан'), ('МЙ', 'майор'), ('ПД', 'подполковник'), ('ПЛ', 'полковник'), ('ГМ', 'генерал-майор'), ('ГЛ', 'генерал-лейтенант'), ('ГП', 'генерал-полковник'), ('ГА', 'генерал армии'), ('АД', 'адъюнкт'), ('ОТ', 'отсутствует')], default='ЛЙ', max_length=2, verbose_name='в/звание'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.CharField(choices=[('2022-08-29', '29-08-2022'), ('2022-08-22', '22-08-2022'), ('2022-08-15', '15-08-2022'), ('2022-08-08', '08-08-2022'), ('2022-08-01', '01-08-2022'), ('2022-07-25', '25-07-2022')], max_length=50, null=True, verbose_name='Дата'),
        ),
    ]
