# Generated by Django 4.0.6 on 2022-11-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_notes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorization',
            name='post',
            field=models.CharField(choices=[('НК', 'заведующий кафедры'), ('ЗК', 'заместитель начальника кафедры'), ('ПР', 'профессор'), ('ДЦ', 'доцент'), ('СП', 'старший преподаватель'), ('ПР', 'преподаватель'), ('ДК', 'докторант'), ('АД', 'аспирант'), ('СН', 'старший научный сотрудник'), ('ЗН', 'заместитель начальника факультета'), ('НЛ', 'начальник лаборатории'), ('НО', 'начальник отделения'), ('ИО', 'инженер отделения'), ('ИП', 'инженер-программист отделения'), ('РМ', 'радиомеханик'), ('ЛБ', 'лаборант'), ('ТХ', 'техник')], default='ПР', max_length=2, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.CharField(choices=[('2022-11-21', '21-11-2022'), ('2022-11-14', '14-11-2022')], max_length=50, null=True, verbose_name='Дата'),
        ),
    ]
