# Generated by Django 4.0.6 on 2022-11-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_autorization_post_alter_notes_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorization',
            name='rank',
        ),
    ]
